Repository YAPP-18th/Android-Team-1-Frontend, pull requests merged in 2021-05, with the labels that each got.

#21 [5월 첫째주 ] 안드로이드 기본 Base 구현
  .github/workflows/android_cd.yml
  README.md
  app/build.gradle
  app/src/main/java/com/engdiary/mureng/constant/AuthConstant.kt
  app/src/main/java/com/engdiary/mureng/di/AuthManager.kt
  app/src/main/java/com/engdiary/mureng/di/Module.kt
  app/src/main/java/com/engdiary/mureng/di/MurengApplication.kt
  app/src/main/java/com/engdiary/mureng/network/MurengRepository.kt
  app/src/main/java/com/engdiary/mureng/network/MurengService.kt
  app/src/main/java/com/engdiary/mureng/ui/base/ActivityResult.kt
  app/src/main/java/com/engdiary/mureng/ui/base/BaseActivity.kt
  app/src/main/java/com/engdiary/mureng/ui/base/BaseFragment.kt
  app/src/main/java/com/engdiary/mureng/ui/base/BaseViewModel.kt
  app/src/main/java/com/engdiary/mureng/util/AnimExt.kt
  app/src/main/java/com/engdiary/mureng/util/CallExt.kt
  app/src/main/java/com/engdiary/mureng/util/DisplayExt.kt
  app/src/main/java/com/engdiary/mureng/util/HorizontalItemDecorator.kt
  app/src/main/java/com/engdiary/mureng/util/ListenerExt.kt
  app/src/main/java/com/engdiary/mureng/util/NavigationExt.kt
  app/src/main/java/com/engdiary/mureng/util/OnSingleClickListener.kt
  app/src/main/java/com/engdiary/mureng/util/RecyclerViewExt.kt
  app/src/main/java/com/engdiary/mureng/util/ResourceExt.kt
  app/src/main/java/com/engdiary/mureng/util/SharedPrefs.kt
  app/src/main/java/com/engdiary/mureng/util/StringExt.kt
  app/src/main/java/com/engdiary/mureng/util/ToastExt.kt
  app/src/main/java/com/engdiary/mureng/util/ViewExt.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: FE

#22 feat/ BottomNavigationBar , Fragment, FragmentViewmodel구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/engdiary/mureng/di/Module.kt
  app/src/main/java/com/engdiary/mureng/ui/home/HomeFragment.kt
  app/src/main/java/com/engdiary/mureng/ui/home/HomeViewModel.kt
  app/src/main/java/com/engdiary/mureng/ui/main/MainActivity.kt
  app/src/main/java/com/engdiary/mureng/ui/main/MainViewModel.kt
  app/src/main/java/com/engdiary/mureng/ui/my/MyPageFragment.kt
  app/src/main/java/com/engdiary/mureng/ui/my/MyPageViewModel.kt
  app/src/main/java/com/engdiary/mureng/ui/social/SocialFragment.kt
  app/src/main/java/com/engdiary/mureng/ui/social/SocialViewModel.kt
  app/src/main/java/com/engdiary/mureng/ui/writing/WritingFragment.kt
  app/src/main/java/com/engdiary/mureng/ui/writing/WritingViewModel.kt
  app/src/main/res/drawable/main_selector_home.xml
  app/src/main/res/drawable/main_selector_my_page.xml
  app/src/main/res/drawable/main_selector_social.xml
  app/src/main/res/drawable/main_selector_writing.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/my_page_fragment.xml
  app/src/main/res/layout/social_fragment.xml
  app/src/main/res/layout/writing_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: FE

#29 [일기작성] 버그 수정
  app/src/main/java/com/engdiary/mureng/network/MurengRepository.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WritingDiaryContentActivity.kt
Labels: Android, bug

#30 [일기작성] 다이어리 작성 화면 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/engdiary/mureng/ui/social/BindingAdapter.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/HintDecoration.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/HintViewHolder.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryContentActivity.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryContentViewModel.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WritingDiaryContentActivity.kt
  app/src/main/res/drawable/sl_hint_bulb.xml
  app/src/main/res/drawable/writediary_header.xml
  app/src/main/res/layout/activity_write_diary_content.xml
  app/src/main/res/layout/activity_writing_diary_image.xml
  app/src/main/res/layout/expandableparent_hint_writingdiary.xml
  app/src/main/res/layout/expandablesecond_hint_writingdiary.xml
Labels: Android, feature

#31 [일기 작성] 사진 선택
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/engdiary/mureng/data/DiaryContent.kt
  app/src/main/java/com/engdiary/mureng/data/ItemWriteDiaryImage.kt
  app/src/main/java/com/engdiary/mureng/data/ItemWritingDiaryImage.kt
  app/src/main/java/com/engdiary/mureng/data/request/PostDiaryRequest.kt
  app/src/main/java/com/engdiary/mureng/data/response/MurengResponse.kt
  app/src/main/java/com/engdiary/mureng/data/response/PostDiaryImageResponse.kt
  app/src/main/java/com/engdiary/mureng/data/response/PostDiaryResponse.kt
  app/src/main/java/com/engdiary/mureng/network/MurengRepository.kt
  app/src/main/java/com/engdiary/mureng/network/MurengService.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/ItemDiaryImageDecoration.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/ItemWriteDiaryGalleryViewHolder.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/ItemWriteDiaryImageViewHolder.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/ItemWritingDiaryGalleryViewHolder.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/ItemWritingDiaryImageViewHolder.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryContentActivity.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryContentViewModel.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryImageActivity.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryImageAdapter.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryImageViewModel.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WritingDiaryImageActivity.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WritingDiaryImageAdapter.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WritingDiaryImageViewModel.kt
  app/src/main/java/com/engdiary/mureng/util/KoreanChecker.kt
  app/src/main/java/com/engdiary/mureng/util/WindowLengthCalculator.kt
  app/src/main/res/layout/activity_write_diary_content.xml
  app/src/main/res/layout/activity_write_diary_image.xml
  app/src/main/res/layout/item_writingdiaryimage_gallery.xml
  app/src/main/res/layout/item_writingdiaryimage_image.xml
  app/src/main/res/values/colors.xml
Labels: Android, feature, network

#32 [일기작성] 선택된 일기 사진의 블러 처리 작업시 사용하는 라이브러리 함수 변경
  app/src/main/java/com/engdiary/mureng/constant/IntentKey.kt
  app/src/main/java/com/engdiary/mureng/network/MurengRepository.kt
  app/src/main/java/com/engdiary/mureng/ui/social/BindingAdapter.kt
Labels: Android, bug

#34 [Module] BASE_URL 끝의 / 제거
  app/src/main/java/com/engdiary/mureng/di/Module.kt
  app/src/main/java/com/engdiary/mureng/network/MurengService.kt
Labels: Android, network

#37 [일기 작성] 통신
  app/src/main/java/com/engdiary/mureng/constant/IntentKey.kt
  app/src/main/java/com/engdiary/mureng/data/Author.kt
  app/src/main/java/com/engdiary/mureng/data/Diary.kt
  app/src/main/java/com/engdiary/mureng/data/DiaryContent.kt
  app/src/main/java/com/engdiary/mureng/data/Hint.kt
  app/src/main/java/com/engdiary/mureng/data/Question.kt
  app/src/main/java/com/engdiary/mureng/data/TodayQuestion.kt
  app/src/main/java/com/engdiary/mureng/data/response/AuthorNetwork.kt
  app/src/main/java/com/engdiary/mureng/data/response/DiaryNetwork.kt
  app/src/main/java/com/engdiary/mureng/data/response/HintNetwork.kt
  app/src/main/java/com/engdiary/mureng/data/response/QuestionNetwork.kt
  app/src/main/java/com/engdiary/mureng/data/response/TodayQuestionResponse.kt
  app/src/main/java/com/engdiary/mureng/network/MurengRepository.kt
  app/src/main/java/com/engdiary/mureng/network/MurengService.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryContentViewModel.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryImageActivity.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryImageViewModel.kt
  app/src/main/res/layout/activity_write_diary_content.xml
Labels: Android, feature

#46 [일기 자세히보기] 일기 자세히보기 뷰, 뷰 동작, 삭제하기 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/engdiary/mureng/constant/IntentKey.kt
  app/src/main/java/com/engdiary/mureng/network/MurengRepository.kt
  app/src/main/java/com/engdiary/mureng/network/MurengService.kt
  app/src/main/java/com/engdiary/mureng/ui/diary_detail/DiaryDetailActivity.kt
  app/src/main/java/com/engdiary/mureng/ui/diary_detail/DiaryDetailViewModel.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryContentActivity.kt
  app/src/main/res/layout/activity_diary_detail.xml
  app/src/main/res/menu/diary_detail_top_app_bar.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Android, feature

#51 [일기 작성] 일기 작성화면의 헤더 색상 변경
  app/src/main/res/drawable/writediary_header.xml
  app/src/main/res/values/colors.xml
Labels: Android, modification

#62 [일기 자세히보기] 일기 작성 화면에서 기존에 존재하는 일기 표시 및 일기 수정 기능 추가
  app/src/main/java/com/engdiary/mureng/constant/IntentKey.kt
  app/src/main/java/com/engdiary/mureng/data/ItemWriteDiaryImage.kt
  app/src/main/java/com/engdiary/mureng/data/request/PutDiaryRequest.kt
  app/src/main/java/com/engdiary/mureng/di/Module.kt
  app/src/main/java/com/engdiary/mureng/network/MurengRepository.kt
  app/src/main/java/com/engdiary/mureng/network/MurengService.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryContentActivity.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryContentViewModel.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryImageActivity.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryImageViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_write_diary_content.xml
  app/src/main/res/values/strings.xml
Labels: Android, feature

#63 [일기 작성] 다이어리 상세보기로 화면 전환 부분 수정
  app/src/main/java/com/engdiary/mureng/constant/IntentKey.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryImageActivity.kt
  app/src/main/java/com/engdiary/mureng/ui/write_diary/WriteDiaryImageViewModel.kt
Labels: Android, feature, fix
